name: YouTube Videos
on:
  push:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  youtube:
    name: latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'YOUTUBE-VIDEOS-LIST'
          max_post_count: 3
          feed_list: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC18oah_ydLjqeCkAxNBNXXA'
          custom_tags: 'channelId/yt:channelId/,videoId/yt:videoId/'
          template: '<tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td><td><a href="$url">$title</a></td></tr>$newline'
          description_max_length: 140
